// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV5WqnVYyci7QTAIMNbXlPwbpu7Mr5XH8',
    appId: '1:819057250674:web:f6d88f711e25574e61cdeb',
    messagingSenderId: '819057250674',
    projectId: 's-rocks-music-db',
    authDomain: 'fir-rocks-music-db.firebaseapp.com',
    storageBucket: 's-rocks-music-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtvS8qBGLO87IBynd9UDSlXyfjS_E6pP0',
    appId: '1:819057250674:android:9d10b351d7607f9761cdeb',
    messagingSenderId: '819057250674',
    projectId: 's-rocks-music-db',
    storageBucket: 's-rocks-music-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH7LCrfexMvbctXlA8LqbaZlGQD0YMYhw',
    appId: '1:819057250674:ios:80603071f2413f3e61cdeb',
    messagingSenderId: '819057250674',
    projectId: 's-rocks-music-db',
    storageBucket: 's-rocks-music-db.firebasestorage.app',
    iosBundleId: 'com.example.sRocksMusicHomepage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH7LCrfexMvbctXlA8LqbaZlGQD0YMYhw',
    appId: '1:819057250674:ios:80603071f2413f3e61cdeb',
    messagingSenderId: '819057250674',
    projectId: 's-rocks-music-db',
    storageBucket: 's-rocks-music-db.firebasestorage.app',
    iosBundleId: 'com.example.sRocksMusicHomepage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV5WqnVYyci7QTAIMNbXlPwbpu7Mr5XH8',
    appId: '1:819057250674:web:66ff5180f109a7cd61cdeb',
    messagingSenderId: '819057250674',
    projectId: 's-rocks-music-db',
    authDomain: 'fir-rocks-music-db.firebaseapp.com',
    storageBucket: 's-rocks-music-db.firebasestorage.app',
  );
}
